// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: password.proto

package passwordpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired password length (validated against a sane min/max).
	Length uint32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	// Which character classes to include. At least one must be true.
	IncludeUppercase bool `protobuf:"varint,2,opt,name=include_uppercase,json=includeUppercase,proto3" json:"include_uppercase,omitempty"`
	IncludeLowercase bool `protobuf:"varint,3,opt,name=include_lowercase,json=includeLowercase,proto3" json:"include_lowercase,omitempty"`
	IncludeDigits    bool `protobuf:"varint,4,opt,name=include_digits,json=includeDigits,proto3" json:"include_digits,omitempty"`
	IncludeSymbols   bool `protobuf:"varint,5,opt,name=include_symbols,json=includeSymbols,proto3" json:"include_symbols,omitempty"`
	// Characters to exclude from the pool (e.g. ambiguous chars). Optional.
	ExcludeChars  string `protobuf:"bytes,6,opt,name=exclude_chars,json=excludeChars,proto3" json:"exclude_chars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_password_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_password_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_password_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GenerateRequest) GetIncludeUppercase() bool {
	if x != nil {
		return x.IncludeUppercase
	}
	return false
}

func (x *GenerateRequest) GetIncludeLowercase() bool {
	if x != nil {
		return x.IncludeLowercase
	}
	return false
}

func (x *GenerateRequest) GetIncludeDigits() bool {
	if x != nil {
		return x.IncludeDigits
	}
	return false
}

func (x *GenerateRequest) GetIncludeSymbols() bool {
	if x != nil {
		return x.IncludeSymbols
	}
	return false
}

func (x *GenerateRequest) GetExcludeChars() string {
	if x != nil {
		return x.ExcludeChars
	}
	return ""
}

type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated password.
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Estimated entropy of the generated password, in bits.
	EntropyBits   float64 `protobuf:"fixed64,2,opt,name=entropy_bits,json=entropyBits,proto3" json:"entropy_bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_password_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_password_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_password_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GenerateResponse) GetEntropyBits() float64 {
	if x != nil {
		return x.EntropyBits
	}
	return 0
}

type CheckStrengthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The password to rate. Never logged or echoed.
	Password      string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStrengthRequest) Reset() {
	*x = CheckStrengthRequest{}
	mi := &file_password_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStrengthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStrengthRequest) ProtoMessage() {}

func (x *CheckStrengthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_password_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStrengthRequest.ProtoReflect.Descriptor instead.
func (*CheckStrengthRequest) Descriptor() ([]byte, []int) {
	return file_password_proto_rawDescGZIP(), []int{2}
}

func (x *CheckStrengthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckStrengthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// zxcvbn score, 0 (weakest) to 4 (strongest).
	Score uint32 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	// Human-readable label derived from the score, e.g. "weak", "strong".
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Estimated entropy in bits.
	EntropyBits float64 `protobuf:"fixed64,3,opt,name=entropy_bits,json=entropyBits,proto3" json:"entropy_bits,omitempty"`
	// Human-readable crack-time estimate, e.g. "3 hours", "centuries".
	CrackTimeEstimate string `protobuf:"bytes,4,opt,name=crack_time_estimate,json=crackTimeEstimate,proto3" json:"crack_time_estimate,omitempty"`
	// Optional suggestions for improving the password.
	Suggestions   []string `protobuf:"bytes,5,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStrengthResponse) Reset() {
	*x = CheckStrengthResponse{}
	mi := &file_password_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStrengthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStrengthResponse) ProtoMessage() {}

func (x *CheckStrengthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_password_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStrengthResponse.ProtoReflect.Descriptor instead.
func (*CheckStrengthResponse) Descriptor() ([]byte, []int) {
	return file_password_proto_rawDescGZIP(), []int{3}
}

func (x *CheckStrengthResponse) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CheckStrengthResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CheckStrengthResponse) GetEntropyBits() float64 {
	if x != nil {
		return x.EntropyBits
	}
	return 0
}

func (x *CheckStrengthResponse) GetCrackTimeEstimate() string {
	if x != nil {
		return x.CrackTimeEstimate
	}
	return ""
}

func (x *CheckStrengthResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_password_proto protoreflect.FileDescriptor

const file_password_proto_rawDesc = "" +
	"\n" +
	"\x0epassword.proto\x12\x16vaultforge.password.v1\"\xf8\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\rR\x06length\x12+\n" +
	"\x11include_uppercase\x18\x02 \x01(\bR\x10includeUppercase\x12+\n" +
	"\x11include_lowercase\x18\x03 \x01(\bR\x10includeLowercase\x12%\n" +
	"\x0einclude_digits\x18\x04 \x01(\bR\rincludeDigits\x12'\n" +
	"\x0finclude_symbols\x18\x05 \x01(\bR\x0eincludeSymbols\x12#\n" +
	"\rexclude_chars\x18\x06 \x01(\tR\fexcludeChars\"Q\n" +
	"\x10GenerateResponse\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12!\n" +
	"\fentropy_bits\x18\x02 \x01(\x01R\ventropyBits\"2\n" +
	"\x14CheckStrengthRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\xb8\x01\n" +
	"\x15CheckStrengthResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\rR\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12!\n" +
	"\fentropy_bits\x18\x03 \x01(\x01R\ventropyBits\x12.\n" +
	"\x13crack_time_estimate\x18\x04 \x01(\tR\x11crackTimeEstimate\x12 \n" +
	"\vsuggestions\x18\x05 \x03(\tR\vsuggestions2\xde\x01\n" +
	"\x0fPasswordService\x12]\n" +
	"\bGenerate\x12'.vaultforge.password.v1.GenerateRequest\x1a(.vaultforge.password.v1.GenerateResponse\x12l\n" +
	"\rCheckStrength\x12,.vaultforge.password.v1.CheckStrengthRequest\x1a-.vaultforge.password.v1.CheckStrengthResponseBNZLgithub.com/martinrgarciap/vaultforge/apps/api/internal/passwordpb;passwordpbb\x06proto3"

var (
	file_password_proto_rawDescOnce sync.Once
	file_password_proto_rawDescData []byte
)

func file_password_proto_rawDescGZIP() []byte {
	file_password_proto_rawDescOnce.Do(func() {
		file_password_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_password_proto_rawDesc), len(file_password_proto_rawDesc)))
	})
	return file_password_proto_rawDescData
}

var file_password_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_password_proto_goTypes = []any{
	(*GenerateRequest)(nil),       // 0: vaultforge.password.v1.GenerateRequest
	(*GenerateResponse)(nil),      // 1: vaultforge.password.v1.GenerateResponse
	(*CheckStrengthRequest)(nil),  // 2: vaultforge.password.v1.CheckStrengthRequest
	(*CheckStrengthResponse)(nil), // 3: vaultforge.password.v1.CheckStrengthResponse
}
var file_password_proto_depIdxs = []int32{
	0, // 0: vaultforge.password.v1.PasswordService.Generate:input_type -> vaultforge.password.v1.GenerateRequest
	2, // 1: vaultforge.password.v1.PasswordService.CheckStrength:input_type -> vaultforge.password.v1.CheckStrengthRequest
	1, // 2: vaultforge.password.v1.PasswordService.Generate:output_type -> vaultforge.password.v1.GenerateResponse
	3, // 3: vaultforge.password.v1.PasswordService.CheckStrength:output_type -> vaultforge.password.v1.CheckStrengthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_password_proto_init() }
func file_password_proto_init() {
	if File_password_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_password_proto_rawDesc), len(file_password_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_password_proto_goTypes,
		DependencyIndexes: file_password_proto_depIdxs,
		MessageInfos:      file_password_proto_msgTypes,
	}.Build()
	File_password_proto = out.File
	file_password_proto_goTypes = nil
	file_password_proto_depIdxs = nil
}
