// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: vaultforge/hash/v1/hash.proto

package hashpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plaintext account password to hash. Never logged or echoed.
	Password      string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashPasswordRequest) Reset() {
	*x = HashPasswordRequest{}
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashPasswordRequest) ProtoMessage() {}

func (x *HashPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashPasswordRequest.ProtoReflect.Descriptor instead.
func (*HashPasswordRequest) Descriptor() ([]byte, []int) {
	return file_vaultforge_hash_v1_hash_proto_rawDescGZIP(), []int{0}
}

func (x *HashPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type HashPasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PHC-encoded Argon2id string, e.g. "$argon2id$v=19$m=...$<salt>$<hash>".
	// Safe to store; contains the salt and parameters needed to verify later.
	PhcHash       string `protobuf:"bytes,1,opt,name=phc_hash,json=phcHash,proto3" json:"phc_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashPasswordResponse) Reset() {
	*x = HashPasswordResponse{}
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashPasswordResponse) ProtoMessage() {}

func (x *HashPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashPasswordResponse.ProtoReflect.Descriptor instead.
func (*HashPasswordResponse) Descriptor() ([]byte, []int) {
	return file_vaultforge_hash_v1_hash_proto_rawDescGZIP(), []int{1}
}

func (x *HashPasswordResponse) GetPhcHash() string {
	if x != nil {
		return x.PhcHash
	}
	return ""
}

type VerifyPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plaintext password to check. Never logged or echoed.
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// The stored PHC hash to verify against.
	PhcHash       string `protobuf:"bytes,2,opt,name=phc_hash,json=phcHash,proto3" json:"phc_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordRequest) Reset() {
	*x = VerifyPasswordRequest{}
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordRequest) ProtoMessage() {}

func (x *VerifyPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordRequest.ProtoReflect.Descriptor instead.
func (*VerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return file_vaultforge_hash_v1_hash_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *VerifyPasswordRequest) GetPhcHash() string {
	if x != nil {
		return x.PhcHash
	}
	return ""
}

type VerifyPasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the password matches the hash. A false value is a NORMAL,
	// successful outcome (wrong password), NOT an error condition.
	Verified      bool `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordResponse) Reset() {
	*x = VerifyPasswordResponse{}
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResponse) ProtoMessage() {}

func (x *VerifyPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultforge_hash_v1_hash_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResponse.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return file_vaultforge_hash_v1_hash_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyPasswordResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_vaultforge_hash_v1_hash_proto protoreflect.FileDescriptor

const file_vaultforge_hash_v1_hash_proto_rawDesc = "" +
	"\n" +
	"\x1dvaultforge/hash/v1/hash.proto\x12\x12vaultforge.hash.v1\"1\n" +
	"\x13HashPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"1\n" +
	"\x14HashPasswordResponse\x12\x19\n" +
	"\bphc_hash\x18\x01 \x01(\tR\aphcHash\"N\n" +
	"\x15VerifyPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x19\n" +
	"\bphc_hash\x18\x02 \x01(\tR\aphcHash\"4\n" +
	"\x16VerifyPasswordResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified2\xd9\x01\n" +
	"\vHashService\x12a\n" +
	"\fHashPassword\x12'.vaultforge.hash.v1.HashPasswordRequest\x1a(.vaultforge.hash.v1.HashPasswordResponse\x12g\n" +
	"\x0eVerifyPassword\x12).vaultforge.hash.v1.VerifyPasswordRequest\x1a*.vaultforge.hash.v1.VerifyPasswordResponseBFZDgithub.com/martinrgarciap/vaultforge/apps/api/internal/hashpb;hashpbb\x06proto3"

var (
	file_vaultforge_hash_v1_hash_proto_rawDescOnce sync.Once
	file_vaultforge_hash_v1_hash_proto_rawDescData []byte
)

func file_vaultforge_hash_v1_hash_proto_rawDescGZIP() []byte {
	file_vaultforge_hash_v1_hash_proto_rawDescOnce.Do(func() {
		file_vaultforge_hash_v1_hash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaultforge_hash_v1_hash_proto_rawDesc), len(file_vaultforge_hash_v1_hash_proto_rawDesc)))
	})
	return file_vaultforge_hash_v1_hash_proto_rawDescData
}

var file_vaultforge_hash_v1_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vaultforge_hash_v1_hash_proto_goTypes = []any{
	(*HashPasswordRequest)(nil),    // 0: vaultforge.hash.v1.HashPasswordRequest
	(*HashPasswordResponse)(nil),   // 1: vaultforge.hash.v1.HashPasswordResponse
	(*VerifyPasswordRequest)(nil),  // 2: vaultforge.hash.v1.VerifyPasswordRequest
	(*VerifyPasswordResponse)(nil), // 3: vaultforge.hash.v1.VerifyPasswordResponse
}
var file_vaultforge_hash_v1_hash_proto_depIdxs = []int32{
	0, // 0: vaultforge.hash.v1.HashService.HashPassword:input_type -> vaultforge.hash.v1.HashPasswordRequest
	2, // 1: vaultforge.hash.v1.HashService.VerifyPassword:input_type -> vaultforge.hash.v1.VerifyPasswordRequest
	1, // 2: vaultforge.hash.v1.HashService.HashPassword:output_type -> vaultforge.hash.v1.HashPasswordResponse
	3, // 3: vaultforge.hash.v1.HashService.VerifyPassword:output_type -> vaultforge.hash.v1.VerifyPasswordResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vaultforge_hash_v1_hash_proto_init() }
func file_vaultforge_hash_v1_hash_proto_init() {
	if File_vaultforge_hash_v1_hash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaultforge_hash_v1_hash_proto_rawDesc), len(file_vaultforge_hash_v1_hash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaultforge_hash_v1_hash_proto_goTypes,
		DependencyIndexes: file_vaultforge_hash_v1_hash_proto_depIdxs,
		MessageInfos:      file_vaultforge_hash_v1_hash_proto_msgTypes,
	}.Build()
	File_vaultforge_hash_v1_hash_proto = out.File
	file_vaultforge_hash_v1_hash_proto_goTypes = nil
	file_vaultforge_hash_v1_hash_proto_depIdxs = nil
}
